apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qbittorrent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:mdg680/homelab-v2.git
    targetRevision: qbtorrent_service
    path: manifests/services/qbittorrent
  destination:
    server: https://kubernetes.default.svc
    namespace: qbittorrent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true