apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-config-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-media
  nfs:
    server: 192.168.1.146
    path: /volume1/Metadata/qbittorrent/config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-downloads-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-media
  nfs:
    server: 192.168.1.146
    path: /volume1/Downloads
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-media-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-media
  nfs:
    server: 192.168.1.146
    path: /volume1/Media
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-data-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-media
  nfs:
    server: 192.168.1.146
    path: /volume1/Data
