---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wireguard-config
  namespace: qbittorrent
spec:
  encryptedData:
    wg0.conf: AgCcwMUkcVeUTUSW+EW8QRsQjZD1cIeFH1D56htSldR0NgS4UwIs2ROWpCjd3UHzxylVPk29AFvoD+6kMEZD9EjRTbm+r1BdZcuucWbnvfAEyPiM2I5Qoy9+3F1SiggT5klVsMij2sGmUtaESEB4rQdw9RaLv/tDvIxAbY+zSrvdG0q2BMW25GZb7/YN7KqtdCc/To//NknO/ZvXWYaxFEExiKDAUwUkKiXpxSp7oN1wUbEwLOUzTxnY79AcDsT06LVp3+ceMNFZxRl3+9kvQPcBk1ND5BYB2j8b6MO93kg7GH7R2qA1cdfHUI4OcWgitAlQDjFJq789GapwQPDXtWkD7A9wDgnZ3pEqfuRuYVE8YS+YLiesSGCtSY4LT8Y4Oi6a2NjTN8hbjtg4vwv/LMumMTZShUiCu2pmyikxnaorA+4YGz1X35HweJ454dfXHGlzET3xON3UBOnsjxssngISeN3HHYxp7Dm1Xk9jKx+DFCGJUFIES6juxuT+ogF9LiAg2VHIFkn9sZJ/dZ0ZNfEGP4KnH3GbTXYfG6YNTfWyAX11zQNhJrZtTbCkniYPRZH1MHv4zKg9l/muU7mbROKGI6tZIkngvpCc372MkrV16Ud0h5PbjR5d1uQW2C883YJy2AMZfKd8ma1aZd3335vRoouB5saOToUmOVq8rOaKoqrNToRkXkBnxLE85tC6Rduu/j6O7WgydC2CuWbDT6PbqVXlJFPYCWTEgsWVXzmO19F4IH0gleEOYdMEw/bveeZ7vgNBBwXCuh8ZaYs/0Bqzhb/YCk8xgqaHAYroL41xch+CqKictHxTo9AdM76M8GIUKmvU0ChNyAfgluwGesNqyPKnlo5xuJtahneLW41xEjqOX9ctPAwhFEhPH9Z2c9rp+prrS6eqbMEhMr8dz/u3nds+9Dq5HoAZ8JEwnnM300kPGdQzrTyGg17dbIJvaLJD6v71tMwCR4A+xQqH3owaMwhPxAJyELMt7zegsTss5sweza/q3is5xRkmhh7BDBKTV5g6DwDzfTc9s503Hbl164QkxP7Y/k9ABkhmOLcZEey8p8ib0bkCq+Yq0sNcAopP43h9F0Gcc5tKjgPR9KY2a0tToJUI2MZ63Z5TssUiNg08na4ydDDW8lr5KkS+rvFJSpMHt6cxSMFDM7GZyryi2QGjFR12I0hYYwchtHw2cLpSD+Z8zQAKoHmK2hiPywgx4WQlPM55tURLvTmPHVxR3TuovbBVZSfUurmFKRxwLwswumnnMzNoRGm5ALiWkyZUUi+8wGk7XqdzL3PU8a80ZMeT5RJnoJn4l/ARob0sHv+oISdkYrN6gIXbUAA=
  template:
    metadata:
      name: wireguard-config
      namespace: qbittorrent
