---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wireguard-config
  namespace: qbittorrent
spec:
  encryptedData:
    wg0.conf: AgBWAgv969hc9u597QtSbfW+RAkZwL1kTGzo4EAA2Zpu5sw+uLijSCvXe4RRZNnDawCkU+xQOEkGtg7RSYODQ8/3v+oiPieZ5/76Yc0RGK7PKt76dEZfUTh/cH4wuFlPIAPPqEqTy/LOXM+hKObPHjXRRHG6+r4Wx2H7gNVzpAV2+9ikwVJnGWKQV+sPY12cqu7Gdetdt/tzhkZm/K7ZyMmg9z9w6pylsQHkLP74dqkkSMs1IfBBY1M+yYyx/DkMRT8xaPHraVHCWFoXsUhr3gE05w9EbtRx/OoltLOqNMx/RB4C2m53Y85ixx8axw0NQ/ws+me+VcaizFL2vWPQZYQ2zbgY2UllfIjhpFVYWgKMAuY9yBANW82OM6ad6PyZkZ6gXAP3G7dT74dgLvxDhM/juZUYghBbbNckujtXVi5ukU6ABBCeEwMWpkqH3MrSf1Vf2bNLItBgnJDIaDCFQP5z4uXRH/5/bUsKCxJQw8/r9plqDcJNqGGNlLEHbYAUSdp7U7v//SJROWOIkC/+vIP5VJN6GmI93Yc5al+7K1CR47D1ReNtLuABJOktnWBqki0u19nketx37oq5uNJXQPUsi/QOfLK8Ij0Ko5Rx7/FIl/CokpzTcXEPz95gRiUezLm3xUG6o/3CrXEBsDBqwrx1T0atbnTl9UBFlgG3XzT3icoNPrQiMMUU8xV/eZLb4DPDZZ4YYMBn3QPwiang2H7xX+s2zM8vNc6O2q6EY83ZRR8ODMevYIeQGDATiRwCyhWEhxPwx54dwtA0bvIgzNHNq3/z9sh6Ea/2TwMhPL59noa+3E/Mrm+xTeWuaIatJDDj1lADXWy1wlzYQyPpMrThxshXgd7QYA3UmPq2SVTluwEk7vrhhaRa7cc0TppOSGJ0sZNiJv2Yq8eALk3oyoB9i29zvc0iSssP6h3LY6oNb8zoxKGrIlXF7H0RWPrW7pm47nAkhAJ2cln6kJrwJMB0s+DL6+M4bqBdDeIxQ97iCEpKPq99cnZCA2Ymzg+o4pIOPkCa4Mj+Ah+DApdRwLXdg5rr779sadL3FFjUVjqf5fiz7twWOglawbAa8G5okNAtiOo2bipdmkF+RUCYxRuuTlc7u15y1tXbKbpi9mynUCNtAvLPnYrQLrx7Dl8a59jQCA+eU93D5G1tTUNwHZo9D73a6Y5A81lTh+5be48XgUL80PBeTxCPzeJUTZIgxRUosd77dL88uunJWynT+EWsK4PB0pvDlVI+r3LJDsIjI6MqqS+wiw/LPEhCuYX2oWwl7cQiK/Qhi4d47z7re+N2DSUwcyn03suvMk1oNfWf4PkCOR9B076WLJGYJVMy
  template:
    metadata:
      name: wireguard-config
      namespace: qbittorrent
