---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wireguard-config
  namespace: qbittorrent
spec:
  encryptedData:
    wg0.conf: AgBjO9HbfO7DYecmdMBVt+JdXZW3QzkZdWANcx+Zmjv/wMx4enYXdQurno6kBF+BrDQdNanKYHF6DioQThAfCyi1Y8N7t7qSawmgmDJ86ujodrVI6yHTDTXd42Pez/Cls3xwsHgfgvD2uHWOW7fBkFWtmXODDyD0R4jBfk4hD7eczu85kevw+99IX5d7FfB7uHuEzTdbg6E2cxWsCETUGxzVwDqYQtkjN0TyoT4oDnuKwBXEVLpaK44EZ5P4bCbXh4H60xmuCyizoTkwbCQlq39LzGKUiMM+nAkVmFWnFg3eU81fa3hoc6R3/mhOV7P+hyvkaHLcasJFckg1ZB7EO33eqkRUymCcRxvT9XIly0KNUB8Q8U7nn1ulVaPn5LG/wyUVS96qCzpQnG7rw3e3/5GX8xFtvbDSaUAERRAGMYqx0DZg5+OXi6Se5T7AZGNarBP5XXsYTdEHRFuKPERwENhtk4hc8tmnPY7/+hgiVYXqFTqnr+xvf780A3J984ZVFmVGE0cUbDIMFY+3L5Le+vQOGWwmtQLa69Y5d5BF2pywgUet64VNcgRPqDx2FkTScx26Bk/6LWXFtxm7T8vOyJfjW6MgUO9LAMSC6h7F7fGge3Sl6cjfg59r9Ez74DxteoH4RBe0aBLoS87Vl40Gep8v11UnGNei3vv07LpNYjZkNg8D/Ae0kQIqWETlM9u12kSmSHvt6FfDsuknKJ21fChw7ikzoFpaGLNDoxttxHTiBy9tPQ/n2DQisDEeYLXnaI1SW3JdEQUaGboUp3DDfHLNQjun/Lg7QHY/FZnj0YjCVJfxUf1se1ouS7BbQ/BfVhodihw2gNpRZIwX3WgEXHoDySAg4ImFKkMT7htW9rbBInRu6tHT9kaKdml1+Oe/ZvRRP+aZnHMnH5dCEFMrA5byVaUC5S7EbdHojterWXFh8YXnIdhXR3YMXl4m+JkYDIQaJml93GgWLlyaTiaMCovNj3VzC8/1evmuTTw5nS9dFeZog8I56CvQHxFeymGJu4+a3JIvWk1qX2qrt0T7saWR6XLG0hB2+4kJYhjhEC0fCuPT46XPSn0/xE0ItepsQtNjNxEg6VSohi4+cBTTp0fORmtIB6qjqeuWTesJpmqd1+zTRZzDVGAb/SQwmGhc7QFmjSKHr5uJ/dg+FTVpIYjmTponbgUPnEx5xdBOU3FULVfmfM6vwff7wXECraKVVnGnYY4J+DOPYfkVxlyvceuJK5xRl1DQpD4gBldYf33ndY/+R0qICRgw/xD908HwoEew6NAW32JAbTrF9CCzGANho1kTxqNoJRynI3XURrgiqHzDexVFbF/xpEaRMeDzkvCmWbhk0GwnPAsS9fNt
  template:
    metadata:
      name: wireguard-config
      namespace: qbittorrent
    type: Opaque
