k3s_cluster:
  children:
    k3s_servers:
      hosts:
        k3s_master-01:
          ansible_host: "{{ vault_k3s_master_ip }}"
    k3s_agents:
      hosts:
        k3s_agent-01:
          ansible_host: "{{ vault_k3s_agent_ip }}"

homelab:
  children:
    k3s_cluster:
  vars:
    ansible_user: "{{ vault_ansible_user }}"
    ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file }}"
    ansible_python_interpreter: /usr/bin/python3
