---
- name: Configure Pi-hole DNS records
  hosts: localhost
  connection: local
  vars_files:
    - ../inventory/group_vars/homelab_vault.yml
  vars:
    traefik_ip: "{{ vault_loadbalancer_ip }}"
    custom_domains:
      - whoami.home
      - jellyfin.home
      - pihole.home
      - argocd.home
      - qbittorrent.home
  tasks:
    - name: Set Pi-hole web password
      kubernetes.core.k8s_exec:
        namespace: pihole
        pod: "{{ lookup('kubernetes.core.k8s', kind='Pod', namespace='pihole', label_selector='app=pihole').metadata.name }}"
        command: pihole setpassword {{ vault_pihole_password }}

    - name: Add custom DNS records to Pi-hole
      kubernetes.core.k8s_exec:
        namespace: pihole
        pod: "{{ lookup('kubernetes.core.k8s', kind='Pod', namespace='pihole', label_selector='app=pihole').metadata.name }}"
        command: pihole -a addcustomdns {{ item }} {{ traefik_ip }}
      loop: "{{ custom_domains }}"
