apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-media
  nfs:
    server: 192.168.50.242
    path: /volume1/Media
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-media
  nfs:
    server: 192.168.50.242
    path: /volume1/Metadata/Jellyfin/com.ugreen.docker.jellyfin/config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-cache-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-media
  nfs:
    server: 192.168.50.242
    path: /volume1/Metadata/Jellyfin/com.ugreen.docker.jellyfin/cache