apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: jellyfin
  labels:
    app: jellyfin
spec:
  type: NodePort
  ports:
    - port: 8096
      targetPort: 8096
      protocol: TCP
      name: http
      nodePort: 30096
  selector:
    app: jellyfin
